import base from './entry-v1.2.js';

const KV='CURATOR_OPS_RECORDS';
const SNAPSHOT_KEY='scheduled-freshness:latest';
const HISTORY_PREFIX='scheduled-freshness:';
const REQUEST_TIMEOUT_MS=10000;
const DISPLAY_TIME_ZONE='America/Chicago';
const SERVICES=[
  {id:'indexer',name:'Curator Indexer',url:'https://curator-indexer.oceanliners.net/api/ops-health'},
  {id:'integrity',name:'Curator Integrity',url:'https://integrity.oceanliners.net/api/ops-health'},
  {id:'site-health',name:'Site Health',url:'https://site-health.oceanliners.net/api/ops-health'},
  {id:'speed',name:'Curator Speed',url:'https://speed.oceanliners.net/api/ops-health'},
  {id:'search-intelligence',name:'Search Intelligence',url:'https://search-intelligence.oceanliners.net/api/ops-health'}
];

export default{
  async fetch(request,env,ctx){const u=new URL(request.url);if(request.method==='GET'&&u.pathname==='/api/scheduled-freshness')return json({ok:true,snapshot:await read(env)});if(request.method==='POST'&&u.pathname==='/api/scheduled-freshness-check-now')return json({ok:true,snapshot:await collect(env,'manual')});if(request.method==='GET'&&u.pathname==='/scheduled')return html(render(await read(env)));return base.fetch(request,env,ctx)},
  async scheduled(controller,env,ctx){const result=base.scheduled(controller,env,ctx);ctx.waitUntil(collect(env,`cron:${controller?.cron||'unknown'}`).catch(e=>console.error('Ops freshness collection failed',e)));return result}
};

async function collect(env,source){requireKv(env);const services=[];for(const s of SERVICES)services.push(await probe(s,env));const counts={healthy:services.filter(x=>x.status==='healthy').length,stale:services.filter(x=>x.status==='stale').length,unknown:services.filter(x=>x.status==='unknown').length,unreachable:services.filter(x=>x.status==='unreachable').length};const snapshot={generatedAt:new Date().toISOString(),source,displayTimeZone:DISPLAY_TIME_ZONE,summary:{total:services.length,...counts,status:counts.stale||counts.unreachable?'attention':counts.unknown?'warming':'healthy'},services};await env[KV].put(SNAPSHOT_KEY,JSON.stringify(snapshot));const ts=Date.parse(snapshot.generatedAt)||Date.now();await env[KV].put(`${HISTORY_PREFIX}${String(9999999999999-ts).padStart(13,'0')}:${crypto.randomUUID()}`,JSON.stringify(snapshot),{expirationTtl:60*60*24*180});return snapshot}
async function probe(s,env){const started=Date.now(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{const target=new URL(s.url);target.searchParams.set('ops',Date.now().toString());const response=await fetch(target.href,{method:'GET',redirect:'follow',cache:'no-store',headers:{accept:'application/json','user-agent':'CuratorOps-Freshness/1.3 (+https://ops.oceanlinercurator.com)',...accessHeaders(env,target)},signal:controller.signal,cf:{cacheTtl:0,cacheEverything:false}});if(!response.ok)throw new Error(`HTTP ${response.status}`);const p=await response.json();return{id:s.id,name:s.name,status:p.status||'unknown',ok:p.ok!==false,lastSuccessAt:p.lastSuccessAt||null,ageMinutes:p.ageMinutes??null,maxAgeMinutes:p.maxAgeMinutes??null,stale:p.stale??null,schedule:p.schedule||null,checkedAt:new Date().toISOString(),durationMs:Date.now()-started}}catch(error){return{id:s.id,name:s.name,status:'unreachable',ok:false,error:error?.name==='AbortError'?'timeout':(error?.message||String(error)),checkedAt:new Date().toISOString(),durationMs:Date.now()-started}}finally{clearTimeout(timer)}}
function accessHeaders(env,target){if(!env.CF_ACCESS_CLIENT_ID||!env.CF_ACCESS_CLIENT_SECRET)return{};const host=target.hostname.toLowerCase();const owned=host==='oceanliners.net'||host.endsWith('.oceanliners.net')||host==='oceanlinercurator.com'||host.endsWith('.oceanlinercurator.com');return owned?{'CF-Access-Client-Id':env.CF_ACCESS_CLIENT_ID,'CF-Access-Client-Secret':env.CF_ACCESS_CLIENT_SECRET}:{}}
async function read(env){requireKv(env);return await env[KV].get(SNAPSHOT_KEY,'json')||{generatedAt:null,source:null,displayTimeZone:DISPLAY_TIME_ZONE,summary:{total:SERVICES.length,healthy:0,stale:0,unknown:SERVICES.length,unreachable:0,status:'unknown'},services:SERVICES.map(s=>({id:s.id,name:s.name,status:'unknown'}))}}
function formatCentral(value){if(!value)return'—';const date=new Date(value);if(Number.isNaN(date.getTime()))return'—';return new Intl.DateTimeFormat('en-US',{timeZone:DISPLAY_TIME_ZONE,month:'numeric',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit',timeZoneName:'short'}).format(date)}
function render(snapshot){const rows=(snapshot.services||[]).map(s=>`<tr><td><span class="dot ${esc(s.status)}"></span>${esc(s.name)}</td><td>${esc(s.status)}</td><td>${s.lastSuccessAt?formatCentral(s.lastSuccessAt):'—'}</td><td>${s.ageMinutes??'—'} min</td><td>${s.maxAgeMinutes??'—'} min</td></tr>`).join(''),x=snapshot.summary||{};return`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Scheduled Work · Curator Ops</title><style>:root{color-scheme:dark;--bg:#0a1110;--panel:#101918;--brass:#bfa46a;--text:#f3eee3;--muted:#9aa6a0;--line:#263330}*{box-sizing:border-box}body{margin:0;background:#0a1110;color:var(--text);font-family:Georgia,serif}.wrap{max-width:1050px;margin:auto;padding:58px 20px}.eyebrow{font:600 12px system-ui;letter-spacing:.18em;text-transform:uppercase;color:var(--brass)}h1{font-size:clamp(38px,7vw,62px);font-weight:400}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:28px 0}.card,.table{border:1px solid var(--line);background:var(--panel);border-radius:16px}.card{padding:18px}.label{font:600 11px system-ui;color:var(--muted);text-transform:uppercase}.value{font-size:28px;margin-top:8px}.table{overflow:auto}table{width:100%;border-collapse:collapse;min-width:760px;font:14px system-ui}th,td{text-align:left;padding:14px;border-bottom:1px solid var(--line)}th{color:var(--muted);font-size:11px;text-transform:uppercase}.dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:9px}.healthy{background:#58c77a}.stale,.unreachable{background:#d86666}.unknown{background:#8b9490}a{color:#e9d49e}.tz{color:var(--muted);font:12px system-ui}</style></head><body><main class="wrap"><div class="eyebrow">CuratorOS · Work Freshness</div><h1>Scheduled Work</h1><p>Confirms that reachable Workers are still completing their scheduled jobs, using each tool's existing Error Bus success heartbeat.</p><p class="tz">Times shown in US Central time (CST/CDT automatically).</p><section class="cards"><div class="card"><div class="label">State</div><div class="value">${esc(x.status||'unknown')}</div></div><div class="card"><div class="label">Healthy</div><div class="value">${x.healthy||0}</div></div><div class="card"><div class="label">Stale</div><div class="value">${x.stale||0}</div></div><div class="card"><div class="label">Unknown</div><div class="value">${(x.unknown||0)+(x.unreachable||0)}</div></div></section><section class="table"><table><thead><tr><th>Worker</th><th>State</th><th>Last success · Central</th><th>Age</th><th>Stale after</th></tr></thead><tbody>${rows}</tbody></table></section><p><a href="/">← Curator Ops</a> · <a href="/deployments">Deployment Drift</a></p></main></body></html>`}
function esc(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}function requireKv(env){if(!env[KV])throw new Error(`${KV} KV binding is not configured.`)}function json(v,s=200){return new Response(JSON.stringify(v,null,2),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'}})}function html(v){return new Response(v,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}})}
